on: [pull_request]
name: build
jobs:
  lint:
    name: "Run hlint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up HLint
      uses: haskell-actions/hlint-setup@v2

    - name: Run HLint
      uses: haskell-actions/hlint-run@v2
      with:
        fail-on: warning

  fourmolu:
    name: "Run fourmolu"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/run-fourmolu@v9
      with:
        version: "0.11.0.0"

  generateMatrix:
    name: "Generate matrix from cabal"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v4
      - name: Extract the tested GHC versions
        id: set-matrix
        run: |
          wget https://github.com/Kleidukos/get-tested/releases/download/v0.1.5.0/get-tested-0.1.5.0-linux-amd64 -O get-tested
          chmod +x get-tested
          ./get-tested --ubuntu free-listt.cabal >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: generateMatrix
    strategy:
      matrix: ${{ fromJSON(needs.generateMatrix.outputs.matrix) }}
    name: Haskell GHC ${{ matrix.ghc }} cabal
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup-haskell-build
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: Cache Cabal build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell-build.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ matrix.ghc }}
          restore-keys: |
            ${{ runner.os }}-cabal-${{ matrix.ghc }}
      - name: Cabal build dependencies
        run: |
          cabal build all  --enable-tests --only-dependencies
      - name: Cabal build packages
        run: |
          cabal build all --enable-tests -fdev
      - name: Cabal test
        run: |
          cabal test all --enable-tests --test-show-details=Always -fdev
